version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled

    ports:
      - 80:80
    depends_on:
      - web

  web:
    container_name: web-server
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn do_it_django_prj.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - ./:/usr/src/app
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
  static_volume:
  media_volume:
