upstream do_it_django {
    server web:8000;
}

server {
    listen 80;
    server_name iamsoon.com;

    location / {
        # HTTP 요청을 HTTPS로 리디렉션
        if ($scheme = http) {
            return 301 https://$server_name$request_uri;
        }
    }

    location /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt/;
    }
}

server {
    listen 443 ssl;
    server_name iamsoon.com;

    location / {
        proxy_pass http://do_it_django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /usr/src/app/_static/;
    }

    location /media/ {
        alias /usr/src/app/_media/;
    }

    location /.well-known/acme-challenge {
        root /var/lib/letsencrypt/;
    }

    ssl_certificate /etc/letsencrypt/live/iamsoon.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/iamsoon.com/privkey.pem;
}