upstream do_it_django {
    server web:8000;
}

server {
    listen 80;
    server_name iamsoon.com;

    location / {
        proxy_pass http://do_it_django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /usr/src/app/_static/;
    }

    location /media/ {
        alias /usr/src/app/_media/;
    }

    location /.well-known/acme-challenge {
        root /var/lib/letsencrypt/;
    }
}

server {
    listen 443 ssl;
    server_name iamsoon.com;

    location / {
        proxy_pass http://do_it_django;  # HTTPS에서도 동일한 upstream 사용
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    ssl_certificate /etc/letsencrypt/live/iamsoon.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/iamsoon.com/privkey.pem;
}
